// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awuulswcvjdqyetnojfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3dXVsc3djdmpkcXlldG5vamZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTU1MjUsImV4cCI6MjA3MTc3MTUyNX0.DTShyp35Nljo2wTcsZkvsfJs8JI62hEQZOxO9fA4iSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});